version: '3'

services:

 dashboard-importer:
    build: dashboard-importer
    networks:
      - ek
    links:
      - elasticsearch
      - kibana

 kibana:
    image: docker.elastic.co/kibana/kibana:5.5.2
    ports:
      - "5601:5601"
    networks:
      - ek
    depends_on:
      - elasticsearch

 elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - http.host=0.0.0.0
      - http.publish_host=127.0.0.1
      - xpack.security.enabled=false
    networks:
      - ek

networks:

  ek:
    driver: bridge
