version: '3'

services:

 dashboard-importer:
    build: dashboard-importer
    networks:
      - ek
    links:
      - elasticsearch
      - kibana

 kibana:
    build: kibana
    ports:
      - "5601:5601"
    networks:
      - ek
    depends_on:
      - elasticsearch

 elasticsearch:
    build: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - http.host=0.0.0.0
# Comment out for making containers reachable from dockerized spark job.
# See README.md for more info:
#      - network.host=_site_
#      - http.publish_host=_site_
    networks:
      - ek

networks:

  ek:
    driver: bridge
